import {StyleSheet, Dimensions} from 'react-native';
import COLORS from '../../GlobalConstants/COLORS';
export default StyleSheet.create({
  container: {flex: 1},
  bottomView: {
    width: '10%',
    //height: 50,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'flex-end',
    position: 'absolute', //Here is the trick
    bottom: 0, //Here is the trick
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  addIconContainer: {
    height: 40,
    width: 40,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: COLORS.lightGreyBorder,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  plusIcon: {
    height: 20,
    width: 20,
  },
  emptyListContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginTop: 50,
  },
  emptyListText: {fontSize: 24, fontWeight: '700', color: COLORS.black},
  listItemContainer: {
    //flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 10,
    //height: 70,
    marginVertical: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    //alignItems: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 1,
  },
  listItemText: {
    color: COLORS.black,
    fontWeight: '500',
    paddingTop: 4,
    textTransform: 'capitalize',
  },
  listItemBoxContainer: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    // alignItems: 'center',
    marginTop: 10,
  },
  listItemStatusText: {fontSize: 12, fontWeight: '700', color: COLORS.black},
  editIcon: {height: 15, width: 15},
  editIconContainer: {
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.lightGreyBorder,
    borderRadius: 5,
    marginTop: 5,
  },
  supplyContainer: {
    flexDirection: 'row',
    //marginTop: 10,
    //height: 26,
    marginHorizontal: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    // borderBottomColor: 'black',
    // borderBottomWidth: 0.4,
    // backgroundColor: 'red',
    paddingBottom: 10,
  },
  newSupplyContainer: {
    width: '48%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottonGroupCotainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
  },
  plusMinusBottonBox: {width: '20%'},
  iconButtonContainer: {
    height: 26,
    borderColor: COLORS.lightGreyBorder,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  iconStyle: {height: 15, width: 15},
  textInputStyle: {
    borderWidth: 1,
    borderColor: 'lightgrey',
    height: 26,
    width: '100%',
    color: 'black',
    paddingVertical: 1,
    paddingHorizontal: 10,
    borderRadius: 5,
    textAlign: 'center',
  },
  disableTextStyle: {
    borderWidth: 1,
    borderColor: 'lightgrey',
    height: 26,
    paddingLeft: 3,
    paddingTop: 3,
    //backgroundColor: 'lightgrey',
    width: '60%',
    color: 'black',
    textAlign: 'center',
  },
});
