export const CHECK_IN_SUCCESS = "CHECK_IN_SUCCESS"
export const CHECK_IN_FAILURE = "CHECK_IN_FAILURE"
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS"
export const CHECK_OUT_FAILURE = "CHECK_OUT_FAILURE"