import {StyleSheet, Dimensions} from 'react-native';
import COLORS from '../../GlobalConstants/COLORS';
export default StyleSheet.create({
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    //paddingHorizontal: 20,
  },
  fromAndTODateCotaier: {
    width: '48%',
    backgroundColor: '#cacaca',
    paddingVertical: 7,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  filterDateText: {color: COLORS.black, fontSize: 12},
  fromAndTODateCotaier: {
    //width: '48%',
    backgroundColor: '#cacaca',
    paddingVertical: 12,
    //borderRadius: 5,
    //flexDirection: 'row',
    //alignItems: 'center',
    paddingHorizontal: 5,
  },
  bottomView: {
    width: '100%',
    //height: 50,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'flex-end',
    position: 'absolute',
    bottom: 0,
    paddingHorizontal: 10,
    paddingBottom: 10,
    //backgroundColor: 'red',
  },
  addIconContainer: {
    height: 40,
    width: 40,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: COLORS.lightGreyBorder,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
    marginVertical: 5,
  },
  plusIcon: {
    height: 20,
    width: 20,
    tintColor: 'red',
  },
  canclebtn: {
    opacity: 4,
    borderRadius: 24,
    //height: hp('6%'),
    justifyContent: 'center',
    alignItems: 'center',
    //marginLeft: 14,
    //marginRight: 48,
    //marginBottom: 24,
    //marginTop: '20%',
    borderColor: '#DA0B0B',
    borderWidth: 2,
    paddingVertical: 10,
    paddingHorizontal: 30,
    backgroundColor: 'white',
  },
  canclebtntext: {
    color: '#DA0B0B',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
